
     module.exports= Sheet1= [
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/glam-roots-women-printed-a-line-kurta/p/itmf7f2e295bfdf9?pid=KTAFVRQ2DMCGZNQE&lid=LSTKTAFVRQ2DMCGZNQEWU9BCV&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_40&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPZbDrNx%2BtwvWXyAbmOvReDx%2B99cDaSjauKCtlMtuJv4iQ%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "GLAM ROOTS Women Printed Cotton Blend A-line Kurta  (Pink)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.8",
            "offer_price": "₹524",
            "oldPrice": "₹1,699",
            "promo": "69% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "GLAMROOTS",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/rani-prints-jaipur-women-floral-print-straight-kurta/p/itmdf1911a7a6a00?pid=KTAFUKJXBHMXHY7W&lid=LSTKTAFUKJXBHMXHY7WLEEYNW&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_9&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFUKJXBHMXHY7W.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Rani Prints Jaipur Women Floral Print Pure Cotton Straight Kurta  (Beige, Red)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4",
            "offer_price": "₹319",
            "oldPrice": "₹949",
            "promo": "66% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "Rani_Prints_jaipur",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/sheqe-women-solid-straight-kurta/p/itmf882gxzyzgrqm?pid=KTAF86VJQTZTYTEC&lid=LSTKTAF86VJQTZTYTECEO9HNK&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_21&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAF86VJQTZTYTEC.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "SHEQE Women Solid Poly Crepe Straight Kurta  (Black)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.9",
            "offer_price": "₹229",
            "oldPrice": "₹999",
            "promo": "77% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "DARJI FASHION",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/n-enterprise-women-printed-high-low-kurta/p/itm2a53748d78e34?pid=KRTFZ8GZTRTTGXWZ&lid=LSTKRTFZ8GZTRTTGXWZBWUOEX&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_36&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPaFSPkfOcbUhwG0XSGftZChgRyl81W9dH29cR%2BqXYZeZw%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "N N ENTERPRISE Women Printed Rayon High Low Kurta  (Purple)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.9",
            "offer_price": "₹524",
            "oldPrice": "₹1,599",
            "promo": "67% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "N N ENTERPRISE",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/omask-women-printed-gown-kurta/p/itmafa4917fd6893?pid=KTAFVU25TGEPV8DG&lid=LSTKTAFVU25TGEPV8DG7UNWO3&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_16&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPbmSEyomFWXIHXjPyVXt2TU%2BbgUYQSJshP%2B7fXPIrmr1A%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Omask Women Printed Rayon Gown Kurta  (Purple)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.2",
            "offer_price": "₹561",
            "oldPrice": "₹2,400",
            "promo": "76% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "JaipurMajestic",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/vbuyz-women-printed-frontslit-kurta/p/itmf4z7fadtrtkt9?pid=KTAF4Z6KS33KD4XN&lid=LSTKTAF4Z6KS33KD4XNYIFM79&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_12&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPb4G0tBTmNWix6rH5cEC817MJWFq%2FIivajLdqzwz5ms5Q%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Vbuyz Women Printed Rayon Frontslit Kurta  (Blue)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4",
            "offer_price": "₹532",
            "oldPrice": "₹2,499",
            "promo": "78% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "Vbuyz",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/glam-roots-women-printed-a-line-kurta/p/itmed249351f9434?pid=KTAFUV6XCADYYXEF&lid=LSTKTAFUV6XCADYYXEFHNLXL5&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_28&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPavcPg%2Fw2Uw%2FcMk%2BI9ylkrGeIGdR5Zf9F%2F0WmaM7BmVpA%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "GLAM ROOTS Women Printed Cotton Blend A-line Kurta  (Light Blue)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.1",
            "offer_price": "₹532",
            "oldPrice": "₹1,599",
            "promo": "66% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "GLAMROOTS",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/miskaat-women-printed-flared-kurta/p/itm0ae3b1c5f8f3d?pid=KTAFTQ9ACQ9FHUPW&lid=LSTKTAFTQ9ACQ9FHUPWYTC58G&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_18&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFTQ9ACQ9FHUPW.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "MISKAAT Women Printed Rayon Flared Kurta  (White, Blue)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.1",
            "offer_price": "₹498",
            "oldPrice": "₹2,999",
            "promo": "83% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "MISKAAT",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/omask-women-printed-a-line-kurta/p/itm0cc7b5357b6c1?pid=KTAFTG2VZGCUXYSE&lid=LSTKTAFTG2VZGCUXYSEUCQMFI&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_32&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPZ6FSCOMcGVVIgFntudKGhU7NrXORmBAYJMug86wTmKxA%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Omask Women Printed Rayon A-line Kurta  (Black)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4",
            "offer_price": "₹411",
            "oldPrice": "₹1,500",
            "promo": "72% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "JaipurMajestic",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/youthnic-women-printed-straight-kurta/p/itm04b1d82b603e4?pid=KTAG5RZCD79HAC5J&lid=LSTKTAG5RZCD79HAC5JMBZGGE&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_25&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAG5RZCD79HAC5J.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Youthnic Women Printed Cotton Blend Straight Kurta  (Multicolor)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.8",
            "offer_price": "₹299",
            "oldPrice": "₹1,596",
            "promo": "81% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "EthnicJunction",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/hellen-vellen-women-solid-flared-kurta/p/itm512ecd38e4be9?pid=KTAGFGC3NWQYCUSJ&lid=LSTKTAGFGC3NWQYCUSJ6XI2MS&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_14&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAGFGC3NWQYCUSJ.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "HELLEN VELLEN Women Solid Rayon Flared Kurta  (Pink)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.1",
            "offer_price": "₹499",
            "oldPrice": "₹1,699",
            "promo": "70% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "HELLENVELLEN",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/kimayra-women-printed-straight-kurta/p/itm0964812a23f95?pid=KTAFVZESGFZDZGMM&lid=LSTKTAFVZESGFZDZGMMLO09RK&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&spotlightTagId=TrendingId_clo%2Fcfv%2Fcib%2Frkt&srno=s_1_38&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFVZESGFZDZGMM.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "KIMAYRA Women Printed Pure Cotton Straight Kurta  (Light Blue)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.7",
            "offer_price": "₹374",
            "oldPrice": "₹1,999",
            "promo": "81% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "EwishRetail",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/yesly-women-solid-anarkali-kurta/p/itma23d6c38a17c0?pid=KTAFXTANQCGJKXVB&lid=LSTKTAFXTANQCGJKXVBPY3P4H&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_35&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFXTANQCGJKXVB.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "YESLY Women Solid Rayon Anarkali Kurta  (Pink)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.1",
            "offer_price": "₹499",
            "oldPrice": "₹1,699",
            "promo": "70% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "GlobalAAA",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/glam-roots-women-printed-gown-kurta/p/itme1062c897347b?pid=KTAFUTMY549XFGYK&lid=LSTKTAFUTMY549XFGYKTBRSCC&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_24&otracker=search&fm=organic&iid=en_l3FU%2BTdnHZEMQdUC4i2obiqiIAkz3LA8rMZxp136NPZkB9N4mIaSriS51Yub8m%2B0DdCoL5EvgXgkkXLLSOBWKg%3D%3D&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "GLAM ROOTS Women Printed Rayon Gown Kurta  (Maroon)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.1",
            "offer_price": "₹499",
            "oldPrice": "₹1,699",
            "promo": "70% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "GLAMROOTS",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/anushansa-women-printed-straight-kurta/p/itmf0ee384048ad6?pid=KTAFY3YAYXWT6ZDG&lid=LSTKTAFY3YAYXWT6ZDG77OSLO&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_3&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFY3YAYXWT6ZDG.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "anushansa Women Printed Cotton Silk Straight Kurta  (Grey, Black)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "3.8",
            "offer_price": "₹319",
            "oldPrice": "₹1,599",
            "promo": "80% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "anushansa",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/hetsa-women-embroidered-straight-kurta/p/itmaa51e544c0d27?pid=KTAFYZ2THE8C3FAD&lid=LSTKTAFYZ2THE8C3FADN3CB8I&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_10&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFYZ2THE8C3FAD.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "Hetsa Women Embroidered Cotton Blend Straight Kurta  (Yellow)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4",
            "offer_price": "₹399",
            "oldPrice": "₹999",
            "promo": "60% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "Amar Tex",
            "description": "",
            "imgSrc": ""
        },
        {
            "category1": "Clothing and Accessories",
            "category2": "Kurtas, Ethnic Sets and Bottoms",
            "category3": "Kurtas",
            "url-href": "https://www.flipkart.com/fashion-depth-women-embroidered-straight-kurta/p/itm4a29c020664d8?pid=KTAFXYQFGXGDBC8F&lid=LSTKTAFXYQFGXGDBC8FGWY7KV&marketplace=FLIPKART&q=kurtas+kurtis&store=clo%2Fcfv%2Fcib%2Frkt&srno=s_1_33&otracker=search&fm=organic&iid=0351ce8e-7e4b-4a6e-aee9-d436c234feb3.KTAFXYQFGXGDBC8F.SEARCH&ppt=None&ppn=None&ssid=lawfyptmww0000001630398407787&qH=5985e3313e9e348f",
            "name": "FASHION DEPTH Women Embroidered Rayon Straight Kurta  (Dark Green)",
            "aggregateRating_ratingCount": "",
            "aggregateRating_reviewCount": "",
            "aggregateRating_ratingValue": "4.2",
            "offer_price": "₹629",
            "oldPrice": "₹1,699",
            "promo": "62% off",
            "warranty": "",
            "highlights": "",
            "offers_seller_name": "FashionDepth",
            "description": "",
            "imgSrc": ""
        }
    ]
